---
title: 'Task 1: Sierra Amphibians'
author: "Lory Salazar"
date: "1/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(readxl)
library(lubridate)
library(patchwork)
```

## Describe here 
etc etc

```{r}
# We begin by reading in the data using read_excel from the readxl package.
amphibians <- read_excel(here("data","sierra_amphibians.xlsx"))

# Create a subset of the data to only include: adult, subadult, and tadpole mountain yellow-legged frogs
yellow_frogs <- amphibians %>% 
  mutate(across(where(is.character), tolower)) %>% 
  filter(amphibian_species == "ramu") %>% 
  filter(amphibian_life_stage == "adult" |
           amphibian_life_stage == "subadult" |
           amphibian_life_stage == "tadpole"
         ) %>% 
  mutate(survey_date = ymd(survey_date)) %>% 
  mutate(year = year(survey_date))

# Next, we will use the group_by function to group the frogs by year, and then take the total count of the frogs for each given year and life stage
frog_count <- yellow_frogs %>% 
  group_by(year) %>% 
  count(amphibian_life_stage, wt = amphibian_number)

# Next, we create a plot of the data. 
ggplot(data = frog_count, aes(fill = amphibian_life_stage, x = year, y = n)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Total mountain yellow-legged frog counts by life stage (1995-2002)",
       x = "Year", y = "Frog counts") +
  theme_minimal()
```

## Describe here
etc etc

```{r}
# First, I create a subset of the data that only had adult and subadult yellow-legged frogs.
adult_yellow <- amphibians %>% 
  mutate(across(where(is.character), tolower)) %>% 
  filter(amphibian_species == "ramu") %>%
  filter(amphibian_life_stage == "adult" |
           amphibian_life_stage == "subadult")

# Here, I create another subset to give us the counts of the top five lakes with the greatest number of yellow-legged frogs.
adult_yellow_ct <- adult_yellow %>% 
  count(lake_id, wt = amphibian_number) %>% 
  slice_max(n, n = 5) %>% 
  mutate(
    lake_id = paste("Lake", lake_id, sep = " ")
    )

# Next, we make a column graph of the top five lakes.
top_five_lakes <- ggplot(data = adult_yellow_ct, aes(x = reorder(lake_id, -n), y = n)) +
  geom_col(width = 0.6) +
  labs(title = "Top five lakes with greatest total adult and subadult \nmountain yellow-legged frog counts (1995-2002)",
       x = "Lake ID", y = "Total frog counts") +
  theme_minimal()
```

## Using `patchwork` for compound figures
```{r}
cmpnd_graph <- total_lakes / top_five_lakes

cmpnd_graph
```

